### ISSUE TITLE
crow+grvl

### ISSUE THREAD

**Issue by DuellingAnts** [andr-ew/gravl#4] opened 2024-01-10 20:26 UTC
using crow to modulate parameters seem to somehow empty norns disk down to 0, making it unresponsive and unable to open scripts (screen stuck on "loading"). had same issue with eels and only way to fix was to flash the disk

**Comment by xmacex** [comment] 2024-03-01 22:05
I noticed the crow issue too, glad to see the issue is already reported here. Here is a slice of the crow error message flood from Maiden, I will see if I can isolate it somehow...

![Screenshot_20240301-224720.jpg](https://github.com/andr-ew/grvl/assets/879300/d885d3ea-fdc3-4076-b9ec-cd53e0ee6a76)

Everything which happens in Maiden goes to system logs, to disk, and eventually fills it up (logging was disabled in the 240221 image). Flood of there error messages is the reason for your disk filling up @DuellingAnts . Flashing disc is unfortunate, but there are other ways, as we discussed here https://llllllll.co/t/norns-not-responding-unable-to-select-scripts/60647?u=xmacex (FYI for future travelers).

The flood also slows the norns UI considerably, it's quite a flood of errors.

I am not sure how I found out about this script, but I had a wonderful time tonight with it – it made amazing soundscapes out of my phone notification sounds under CV control! I hope the script will be released at some point for people to enjoy :)

**Comment by xmacex** [comment] 2024-03-02 23:45
Here is the beginning of the plugging in crow

```
Mar  2 23:41:25 norns ws-wrapper[475]: dev_monitor: vendor=monome___whimsical_raps model=crow:_telephone_line
Mar  2 23:41:25 norns ws-wrapper[475]: tty is a crow
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011method '__newindex'
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011repl:1: in main chunk
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011runtime error.
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011bad argument #2 to 'casl_setdynamic' (number expected, got nil)                                           
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011stack traceback:
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011[C]: in function 'casl_setdynamic'
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011?: in metamethod '__newindex'
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011repl:1: in main chunk
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011runtime error.
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011event queue full!
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011event queue full!
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011event queue full!
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011event queue full!
Mar  2 23:41:25 norns ws-wrapper[475]: crow:#011bad argument #2 to 'casl_setdynamic' (number expected, got nil)
```

… and plenty more of the same. The flood stops when I pull the plug on crow.

**Comment by andr-ew** [comment] 2024-09-03 05:49
@DuellingAnts I suspect the primary space disk issue was addressed with the latest norns release removing logging. but just in case (& to address general legginess with the feature) I did a pass at hopefully improving performance with the latest 0.3 update of grvl using my improved patching library

I'm going to close this but if you run into issues with the new update please re-open here or otherwise ping me : )

**Closed as completed by andr-ew** 2024-09-03 05:49 UTC
